### ISSUE TITLE
Problem with var in ansible 2.2

### ISSUE THREAD

**Issue by rob42** [yetu/ansible-hostname#2]
These lines in main.yml fail in 2.2, the syntax has changed:
```
- name: Ensure hostname entries in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  with_items: hostname_hosts_file
```
Need to change last line to:
```
  with_items: "{{hostname_hosts_file}}"
```
